"""empty message

Revision ID: 6cfa3d31de1a
Revises: 4c5cab2b8782
Create Date: 2018-03-31 02:22:57.196687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfa3d31de1a'
down_revision = '4c5cab2b8782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isadm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isadm')
    # ### end Alembic commands ###
