"""empty message

Revision ID: ebcb84f59d0c
Revises: 
Create Date: 2018-04-12 22:28:16.294055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcb84f59d0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('pin', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('isadm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user'), 'users', ['user'], unique=True)
    op.create_table('xiangmus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xiangmu', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bujuans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jine', sa.Integer(), nullable=True),
    sa.Column('outtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('xiangmu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['xiangmu_id'], ['xiangmus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bujuans')
    op.drop_table('xiangmus')
    op.drop_index(op.f('ix_users_user'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
